CREATE TABLE IF NOT EXISTS relay_details (
    created_at timestamp,
    fingerprint varchar(40),
    nickname varchar(20),
    running boolean,
    measured boolean,
    asn varchar(10),
    as_name varchar(40),
    consensus_weight smallserial,
    platform varchar(40),
    version varchar(20),
    country varchar(10),
    country_name varchar(10),
    contact varchar(200),
    flags varchar(10)[],
    first_seen timestamp,
    last_seen timestamp,
    last_changed timestamp,
    bandwidth_rate bigserial,
    bandwidth_burst bigserial,
    observed_bandwidth bigserial,
    advertised_bandwidth bigserial,
    guard_probability NUMERIC(7, 6),
    middle_probability NUMERIC(7, 6),
    exit_probability NUMERIC(7, 6),
    UNIQUE (created_at, fingerprint)
)